import Navbar from "@/components/navbar";
import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import Footer from '../components/footer';
import Home from './home/index';

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>my-app</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <Navbar />
      <Home />
      <Footer />

    </>
  );
};

export default Index;
